import {
  Cloud,
  CloudAlert,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  DropletOff,
  Flame,
  Haze,
  Snowflake,
  Sun,
  Tornado,
  Volleyball,
  Waves,
  Wind,
} from "lucide-react";

export const weatherIcons = {
  Clear: Sun,
  Clouds: Cloud,
  Drizzle: CloudDrizzle,
  Rain: CloudRain,
  Thunderstorm: CloudLightning,
  Snow: Snowflake,
  Smoke: Flame,
  Haze: Haze,
  Dust: DropletOff,
  Fog: Waves,
  Sand: Volleyball,
  Ash: CloudAlert,
  Squall: Wind,
  Tornado: Tornado,
  Mist: CloudFog,
};

// export const weatherIcons = {
//   Clear: "https://cdn.weatherapi.com/weather/64x64/day/113.png",
//   Clouds: "https://cdn.weatherapi.com/weather/64x64/day/119.png",
//   Drizzle: "https://cdn.weatherapi.com/weather/64x64/day/263.png",
//   Rain: "https://cdn.weatherapi.com/weather/64x64/day/308.png",
//   Thunderstorm: "https://cdn.weatherapi.com/weather/64x64/day/389.png",
//   Snow: "https://cdn.weatherapi.com/weather/64x64/day/338.png",
//   Mist: "https://cdn.weatherapi.com/weather/64x64/day/143.png",
  // Dust: DropletOff,
  // Fog: Waves,
  // Sand: Volleyball,
  // Ash: CloudAlert,
  // Squall: Wind,
  // Tornado: Tornado,
  // Mist: CloudFog,
// };
